// ==UserScript==
// @name         Utilities
// @description  Some of functions
// @version      1.2
// @author       N3onTechF0X
// @match 		   https://*.tankionline.com/*
// @icon 		     https://www.google.com/s2/favicons?sz=64&domain=tankionline.com
// @run-at 		   document-start
// @grant 		   none
// ==/UserScript==

const floatingWindow=document.createElement("div");floatingWindow.style.cssText="position: fixed; top: 20px; left: 20px; background-color: black; padding: 10px; border: 4px solid #8B00FF; display: none; border-radius: 15px; z-index: 9999; color: #8B00FF; font-size: 20px;";const toggle1=document.createElement("div");let conts_interval;function buy_conts(){const e=["120 ящиков","Подтвердить","Закрыть"];document.querySelectorAll("span").forEach((t=>{e.includes(t.textContent)&&t.click()}))}toggle1.textContent="Открыть контейнеры",toggle1.addEventListener("click",(()=>{floatingWindow.style.display="none";for(var e=0;e<1e3;e++)document.querySelector(".ClosedContainerStyle-moreButton")?.click()}));const toggle2=document.createElement("div");toggle2.textContent="Купить контейнеры",toggle2.addEventListener("click",(()=>{is_conts_buy=!is_conts_buy,is_conts_buy?conts_interval=setInterval(buy_conts,200):clearInterval(conts_interval)}));let golds_interval,is_conts_buy=!1;function hide_golds(){document.querySelectorAll(".ksc-0.BattleMessagesComponentStyle-messageRow").forEach((e=>{const t=e.querySelector(".ksc-0.BattleMessagesComponentStyle-message");if(t){const n=t.innerHTML.toLowerCase();n.includes("золотой")||n.includes("ящик")||n.includes("golden")||n.includes("box")?e.style.display="none":e.style.display="flex"}}))}const toggle3=document.createElement("div");toggle3.textContent="Спрятать голды",toggle3.addEventListener("click",(()=>{if(is_golds_hide=!is_golds_hide,is_golds_hide)golds_interval=setInterval(hide_golds,10);else{clearInterval(golds_interval);document.querySelectorAll(".ksc-0.BattleMessagesComponentStyle-messageRow").forEach((e=>{e.style.display="flex"}))}}));let is_golds_hide=!1;document.addEventListener("keydown",(e=>{"p"===e.key&&("none"===floatingWindow.style.display?floatingWindow.style.display="block":floatingWindow.style.display="none")})),floatingWindow.appendChild(toggle1),floatingWindow.appendChild(document.createElement("p")),floatingWindow.appendChild(toggle2),floatingWindow.appendChild(document.createElement("p")),floatingWindow.appendChild(toggle3),document.body.appendChild(floatingWindow);
