// ==UserScript==
// @name         Utilities
// @description  Some of functions
// @version      1.4
// @author       N3onTechF0X, tdsrse
// @match        https://*.tankionline.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tankionline.com
// @run-at       document-start
// @grant        none
// ==/UserScript==

const floatingWindow=document.createElement("div");floatingWindow.style.cssText="position: fixed; top: 20px; left: 20px; background-color: rgb(0 0 0/30%); padding: 10px; backdrop-filter: blur(5px); border: 2px solid rgba(255, 255, 255, 0.2); display: none; border-radius: 15px; z-index: 9999; font-size: 17px; color: white; transition: opacity 0.5s, transform 0.5s ease-in-out;";const toggle1=document.createElement("div");let conts_interval;function buy_conts(){const e=["120 ящиков","Подтвердить","Закрыть"];document.querySelectorAll("span").forEach((t=>{e.includes(t.textContent)&&t.click()}))}toggle1.textContent="Open Containers",toggle1.style.cssText="width: 160px; background-color: transparent; border: 2px solid rgba(255, 255, 255, 0.20); border-radius: 15px; text-align: center;",toggle1.addEventListener("click",(()=>{floatingWindow.style.display="none";for(var e=0;e<1e3;e++)document.querySelector(".ClosedContainerStyle-moreButton")?.click()}));const toggle2=document.createElement("div");toggle2.textContent="Buy Containers",toggle2.style.cssText="width: 160px; background-color: transparent; border: 2px solid rgba(255, 255, 255, 0.2); border-radius: 15px; text-align: center;",toggle2.addEventListener("click",(()=>{is_conts_buy=!is_conts_buy,is_conts_buy?(conts_interval=setInterval(buy_conts,200),toggle2.style.backgroundColor="rgb(66 150 66/30%)"):(clearInterval(conts_interval),toggle2.style.backgroundColor="transparent")}));let golds_interval,is_conts_buy=!1;function hide_golds(){document.querySelectorAll(".BattleMessagesComponentStyle-messageRow").forEach((e=>{const t=e.querySelector(".BattleMessagesComponentStyle-message");if(t){const o=t.innerHTML.toLowerCase();o.includes("золотой")||o.includes("ящик")||o.includes("golden")||o.includes("box")?e.style.display="none":e.style.display="flex"}}))}const toggle3=document.createElement("div");toggle3.textContent="Hide Golds",toggle3.style.cssText="width: 160px; background-color: transparent; border: 2px solid rgba(255,255,255,0.2); border-radius: 15px; text-align: center;",toggle3.addEventListener("click",(()=>{if(is_golds_hide=!is_golds_hide,is_golds_hide)golds_interval=setInterval(hide_golds,10),toggle3.style.backgroundColor="rgb(66 150 66/30%)";else{clearInterval(golds_interval);document.querySelectorAll(".BattleMessagesComponentStyle-messageRow").forEach((e=>{e.style.display="flex"})),toggle3.style.backgroundColor="transparent"}}));let is_golds_hide=!1;document.addEventListener("keydown",(e=>{77===e.keyCode&&(!document.querySelector('input'))&&("none"===floatingWindow.style.display?floatingWindow.style.display="block":floatingWindow.style.display="none")})),floatingWindow.appendChild(toggle1),floatingWindow.appendChild(document.createElement("p")),floatingWindow.appendChild(toggle2),floatingWindow.appendChild(document.createElement("p")),floatingWindow.appendChild(toggle3),document.body.appendChild(floatingWindow);
